services:
  postgres:
    image: postgres:16-alpine
    container_name: payrollpro-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: payroll_user
      POSTGRES_PASSWORD: payroll_secret
      POSTGRES_DB: payrollpro
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
